providers = ["node"]

[variables]
PORT = "80"
NIXPACKS_SPA_CADDY = "false"

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "PORT=80 node server.js"
